export const reportData = {
  generatedAt: '2026-05-24 KST',
  codex: {
    lane: 'Codex',
    folder: '태양계프로젝트 - codex',
    branch: 'master',
    remote: 'https://github.com/gmpark-creator/project-dashboard.git',
    currentStep: 'Step 9',
    latestImplementationCommit: '3822b6f Enhance Codex solar project with Claude parity layers',
    latestTrackingCommit: 'pending Step 9 metadata commit',
    appUrl: './index.html',
    strengths: [
      'Date-object based ephemeris path is retained for planet and Moon placement.',
      'Baseline reset is fixed to 2026-05-22 as requested.',
      'Playwright verification covers desktop/mobile rendering, date jumps, speed presets, click focus, info panel, and overview return.',
      'Kuiper Belt and Oort Cloud are rendered as particle systems on the same AU scale as the planetary scene.',
      'Interstellar focus targets add Alpha Centauri and 40 Eridani A with light-year distances and long-range camera transitions.',
      'Focus menu now includes a whole-solar-system overview and a Sagittarius A* event-horizon landmark.',
      'Sagittarius A* now uses a cinematic procedural black-hole view with accretion disk, lensing arcs, halo, and jet layers.',
      'Claude 2026-05-24 feature set has been reimplemented in the Codex lane as separate moon, probe, Lagrange, exotic, and Interstellar layers.',
      'Claude latest mobile panel-close workflow is mirrored with Codex-owned close buttons and a restore-chip dock.',
      'Codex keeps the implementation split across app JS, report JS, report data, and styles instead of merging into the Claude single-file simulator.',
      'Code is separated into HTML, CSS, app JS, report JS, and data files for maintainability.',
      'Peer tracking is recorded under internal/peer without modifying the Claude folder.',
    ],
    openItems: [
      'Continue low-end mobile WebGL checks as particle and shader-like visual layers increase.',
      'Tide mode is intentionally not promoted until harmonic constants and local corrections are specified.',
      'Next recommended slice: source/accuracy panel and higher-precision ephemeris for spacecraft and hypothetical bodies.',
    ],
  },
  claude: {
    lane: 'Claude',
    folder: 'solar-project-claude',
    branch: 'master',
    remote: 'https://github.com/gmpark-creator/project-dashboard.git',
    currentStep: '2026-05-24 Claude expansion',
    localHead: '7e67296',
    remoteHead: '7e67296',
    liveUrl: '../solar-project-claude/',
    reportSource: '../solar-project-claude/index.html',
    strengths: [
      'Claude lane added major moon systems, spacecraft, Lagrange/co-orbital objects, Oumuamua, Planet Nine, Interstellar scenes, EHT black hole, and mobile panel controls.',
      'The latest Claude lane keeps its own public folder and is not edited by Codex in this pass.',
      'Codex used Claude output as reference material only and reimplemented the feature groups in the Codex architecture.',
    ],
    concerns: [
      'Claude lane remains a very large single HTML file, so initialization-order regressions require extra browser checks.',
      'The Codex port intentionally uses simplified deterministic positions for spacecraft and speculative bodies until authoritative ephemerides are added.',
      'Both lanes still need a dedicated source/accuracy disclosure panel for non-operational tide and simplified orbital models.',
    ],
  },
  metrics: [
    { label: 'Bodies Rendered', value: '46+', detail: 'Planets, Moon, 11 major moons, 5 probes, Lagrange points, co-orbital/exotic bodies, black holes, wormhole, and Interstellar planets' },
    { label: 'Codex Verification', value: 'PASS', detail: 'Desktop screenshots for moons, Voyager, EHT, Gargantua plus mobile Gargantua check' },
    { label: 'Lane Separation', value: 'Clean', detail: 'Codex changes stay under solar-project-codex and Codex report files' },
    { label: 'Baseline Date', value: '2026-05-22', detail: 'Fixed reset retained in Codex lane' },
  ],
  featureMatrix: [
    { area: 'Major Moons', codex: '11 moon layer', status: 'Implemented', detail: 'Phobos, Deimos, Io, Europa, Ganymede, Callisto, Titan, Rhea, Titania, Oberon, and Triton are selectable with parent-planet visibility rules.' },
    { area: 'Human Spacecraft', codex: 'Probe layer', status: 'Implemented', detail: 'Voyager 1/2, New Horizons, Parker Solar Probe, and JWST use Codex-built marker/model groups and independent focus entries.' },
    { area: 'Lagrange & Co-orbital', codex: 'Equilibrium layer', status: 'Implemented', detail: 'Earth-Sun L1-L5, Jupiter Trojan clouds, and Kamoʻoalewa are separated behind the Lagrange toggle.' },
    { area: 'Exotic Bodies', codex: 'Oumuamua + Planet Nine + EHT', status: 'Implemented', detail: 'Oumuamua path, Planet Nine model orbit, and an EHT M87* black-hole scene are grouped under the Exotic toggle.' },
    { area: 'Interstellar', codex: 'Wormhole + Gargantua scene', status: 'Implemented', detail: 'Wormhole near Saturn, Gargantua, and Miller/Mann/Edmunds planets are available as a separate Interstellar layer.' },
    { area: 'Mobile Panel UX', codex: 'Close + restore dock', status: 'Implemented', detail: 'HUD, info, and Busan moon/tide panels can be closed and restored through lightweight Codex chips.' },
    { area: 'Reports', codex: 'Parity map + evidence', status: 'Upgraded', detail: 'The report now explains feature parity, lane separation, verification evidence, and handoff boundaries.' },
  ],
  timeline: [
    {
      step: 'Step 1',
      title: 'Sun, Earth, Moon foundation',
      date: '2026-05-21',
      codex: ['Three.js scene', 'OrbitControls', 'Sun/Earth/Moon', 'GMST Earth rotation', 'Moon perturbation model'],
      claude: ['Space background', 'Camera controls', 'Sun/Earth/Moon real-time implementation'],
    },
    {
      step: 'Step 2',
      title: 'Major planet expansion',
      date: '2026-05-21',
      codex: ['7 additional major planets', 'Keplerian positions', 'Orbit lines', 'Focus dropdown', 'Saturn ring'],
      claude: ['8-planet expansion', 'Keplerian ephemeris', 'Saturn rings', 'Earth texture upgrade'],
    },
    {
      step: 'Step 3',
      title: 'Time navigation and tide track split',
      date: '2026-05-22',
      codex: ['Direct datetime input', '+/- day controls', '+/- 730 day slider', 'Live reset', 'Time-control verification'],
      claude: ['Theoretical tide panel', 'Tidal bulge', '48-hour curve', 'Web deployment'],
    },
    {
      step: 'Step 4',
      title: 'Interaction and visual upgrade',
      date: '2026-05-22',
      codex: ['Fixed 2026-05-22 reset', 'Calendar jump buttons', '1x/10x/100x presets', 'Click focus', 'Info panel', 'Shadows and ring texture'],
      claude: ['Time-machine UI', 'Speed slider', 'Click interaction', 'Info sidebar', 'Labels', 'Shadow map'],
    },
    {
      step: 'Step 5',
      title: 'Outer solar system structures',
      date: '2026-05-23',
      codex: ['Kuiper Belt particle torus at 30-50 AU', 'Oort Cloud spherical shell at 2,000-100,000 AU', 'Outer-region focus menu', 'Dynamic AU/km distance readouts', 'Long-range camera depth and smooth zoom'],
      claude: ['Pending cross-review in Claude lane'],
    },
    {
      step: 'Step 6',
      title: 'Conditional boundaries and interstellar landmarks',
      date: '2026-05-23',
      codex: ['Kuiper/Oort hidden by default and shown only on focus', 'CSS2D boundary labels with distance ranges', 'Alpha Centauri triple-star landmark', '40 Eridani A Project Hail Mary landmark', 'Busan tide table and live moon phase widget'],
      claude: ['Pending cross-review in Claude lane'],
    },
    {
      step: 'Step 7',
      title: 'System overview and event horizon focus',
      date: '2026-05-24',
      codex: ['Focus dropdown includes 태양계 전체', 'Overview button now returns to the full system frame', 'Sagittarius A* 사건의 지평선 focus item', 'Black-hole boundary mesh with photon-ring style glow', 'Event-horizon distance and physical radius readouts'],
      claude: ['Pending cross-review in Claude lane'],
    },
    {
      step: 'Step 8',
      title: 'Cinematic black-hole visual pass',
      date: '2026-05-24',
      codex: ['Procedural accretion disk texture', 'Layered event-horizon core mask and halo', 'Lensing rings, disk sparks, and faint polar jets', 'Camera framing now moves close enough to inspect the black-hole scene'],
      claude: ['Pending cross-review in Claude lane'],
    },
    {
      step: 'Step 9',
      title: 'Claude parity layer implemented in Codex lane',
      date: '2026-05-24',
      codex: ['11 major moons', '5 human spacecraft', 'L1-L5 + Jupiter Trojans + Kamoʻoalewa', 'Oumuamua + Planet Nine + EHT M87*', 'Wormhole + Gargantua + Miller/Mann/Edmunds', 'Panel close/restore dock', 'Report feature matrix and evidence section'],
      claude: ['Reference lane only; no Claude files edited by Codex'],
    },
  ],
  verification: [
    'Static syntax checks pass for `solar-project-codex/src/app.js`, report data, report renderer, and the main Codex dashboard data.',
    'Desktop viewport 1440x900 renders nonblank canvas with expected controls.',
    'Mobile viewport 390x844 renders nonblank canvas with wrapped controls.',
    'Desktop and mobile Playwright screenshots confirm Kuiper Belt and Oort Cloud focus modes render nonblank WebGL frames.',
    'Conditional visibility checks confirm Kuiper/Oort boundary systems are hidden until selected.',
    'Interstellar focus checks confirm Alpha Centauri and 40 Eridani A show light-year distance readouts.',
    'System overview focus checks confirm 태양계 전체 appears in the focus menu and frames the planetary system.',
    'Event Horizon focus checks confirm the Sagittarius A* boundary visual is hidden by default and shown only when selected.',
    'Black-hole focus check confirms the event horizon has visible accretion-disk, lensing-ring, halo, and jet layers.',
    'Direct focus URL `?focus=event-horizon` opens the black-hole scene for screenshot and Claude review.',
    'Direct focus URL `?focus=ganymede` confirms the Codex major-moon layer renders near Jupiter.',
    'Direct focus URL `?focus=voyager1` confirms the probe layer renders and frames a spacecraft marker/model.',
    'Direct focus URL `?focus=eht-blackhole` confirms the EHT M87* black-hole scene renders independently from Sagittarius A*.',
    'Direct focus URL `?focus=gargantua` confirms the Interstellar black-hole scene and its orbiting planets render on desktop and mobile.',
    'Panel close/restore implementation adds HUD, info, and Busan moon/tide close controls plus restore chips without changing Claude files; screenshots confirm the controls render.',
    'Busan tide table defaults to Busan and renders current water level, next tide events, and a compact tide curve.',
    'Live moon widget uses current system time and validates 2026-05-23 23:24 KST as 상현전 초승달 at about 44-45% illumination.',
    'Mobile layout check confirms Oort Cloud information panel does not overlap the timebar or toolbar.',
    'Date reset returns to 2026-05-22.',
    '+1 week jump resolves to 2026-05-29.',
    '100x speed preset readout is verified.',
    'Earth click focus opens the information panel.',
    'Overview return hides the panel and frames the full solar-system view.',
  ],
  redTeam: [
    'Do not treat either lane tide visualization as operational tide prediction until local harmonic constants are introduced.',
    'Keep Claude folder read-only from Codex; cross-review through git/README/browser evidence only.',
    'Codex handoff should stay current so Claude can review the public Codex lane without touching Codex-owned files.',
    'Do not merge Claude single-file code into Codex directly; keep feature parity but preserve the Codex module boundaries.',
    'Before merging lanes, compare reset semantics, Earth rotation formula, and tide accuracy claims.',
  ],
  evidence: [
    { type: 'Screenshot', title: 'Gargantua desktop/mobile', detail: 'Playwright screenshots verified the Interstellar black-hole scene at 1440x900 and 390x844 viewports.' },
    { type: 'Screenshot', title: 'Ganymede moon layer', detail: 'Direct focus rendering shows a selectable major moon near Jupiter with the moon-layer visibility rule active.' },
    { type: 'Screenshot', title: 'Voyager and EHT', detail: 'Probe and EHT black-hole focus URLs rendered nonblank WebGL frames without touching the Claude lane.' },
    { type: 'Handoff', title: 'CODEX_TO_CLAUDE.md', detail: 'Claude can review the Codex Step 9 parity pass from the Codex handoff file and public Codex URL.' },
    { type: 'UX', title: 'Panel restore dock', detail: 'Codex now mirrors Claude latest panel-close workflow through independent restore chips for the HUD, info panel, and Busan stack.' },
    { type: 'Boundary', title: 'Separate folders', detail: 'Codex implementation remains under `solar-project-codex`; Claude output remains under `solar-project-claude`.' },
    { type: 'Risk', title: 'Simplified ephemeris', detail: 'Spacecraft, Planet Nine, and Interstellar objects are educational visual models, not mission-grade trajectory products.' },
  ],
};
