export const reportData = {
  generatedAt: '2026-05-24 KST',
  projects: [
    {
      id: 'ship',
      order: '01',
      name: 'AIS Ship Tracker',
      label: '선박 위치 추적 운영판',
      state: '운영 공개',
      health: 'strong',
      progress: 100,
      stack: ['Next.js', 'React', 'TypeScript', 'Leaflet', 'Vercel'],
      summary: '관리 대상 선단을 지도 위에서 실시간으로 확인하는 선박 위치 추적 웹앱.',
      verdict: '실제 운영 화면과 공개 URL이 갖춰져 있어 현재 프로젝트군에서 제품 표면이 가장 분명하다.',
      links: [
        {
          label: 'ops-main',
          url: 'https://ais.vercel.co.kr/ops-main',
          probe: 'HTTP 200',
          note: 'PEL / MAGE / OCEAN ACE 운영 화면',
        },
        {
          label: 'kyowa-line-ops',
          url: 'https://ais.vercel.co.kr/kyowa-line-ops',
          probe: 'HTTP 200',
          note: 'KYOWA LINE 분리 운영 화면',
        },
      ],
      review: [
        '지도 기반 선박 추적이라는 목적이 분명하고, 선박별 URL 분리도 운영 업무에 맞다.',
        '다음 단계는 기능 추가보다 AIS 데이터 공급원, 갱신 주기, 장애 fallback 정책을 고정하는 쪽이 우선이다.',
        '노선과 선사별 버전이 늘어날수록 공통 코드와 설정 파일을 분리해서 drift를 줄여야 한다.',
      ],
      risks: [
        { level: 'medium', text: 'AIS 데이터 공급 방식과 장애 시 표시 정책이 명확하지 않으면 운영 신뢰도가 흔들릴 수 있다.' },
        { level: 'low', text: '노선별 배포가 늘어날수록 설정 차이를 추적하는 configuration matrix가 필요하다.' },
      ],
      next: [
        'AIS 데이터 공급원, 갱신 주기, 실패 fallback을 운영 문서로 고정.',
        '노선별 차이를 설정 파일로 분리하고 공통 컴포넌트 변경을 한 번에 반영.',
      ],
    },
    {
      id: 'sports',
      order: '02',
      name: 'Sports Highlight Generator',
      label: '스포츠 하이라이트 생성기',
      state: '데이터 경로 보류',
      health: 'paused',
      progress: 78,
      stack: ['HTML5 Canvas', 'JavaScript', 'Tailwind CSS', 'Metrica sample data'],
      summary: '선수와 공의 위치 데이터를 2D 경기장에 재생하고, 장면 분석과 하이라이트 자동화를 목표로 하는 프로젝트.',
      verdict: '기술 데모로는 가치가 있지만 제품 판단은 멈추는 것이 맞다. 최신 경기의 연속 트래킹 데이터 확보가 핵심 병목이다.',
      links: [
        {
          label: '2D Match Tracker',
          url: 'https://gmpark-creator.github.io/project-dashboard/match-tracker/',
          probe: 'HTTP 200',
          note: 'Metrica 공개 샘플 기반 미리보기',
        },
      ],
      review: [
        '현재 구현은 하이라이트 생성기라기보다 트래킹 데이터 리플레이어에 가깝다.',
        'Metrica 공개 샘플 기반 데모로는 충분하지만, 최신 실경기 자동 생성으로 부르기에는 데이터 라이선스가 먼저 해결되어야 한다.',
        '제품 방향은 유료 optical tracking 라이선스 확보 또는 공개 이벤트 데이터 기반 분석 도구로 범위를 줄이는 두 갈래가 현실적이다.',
      ],
      risks: [
        { level: 'high', text: '최신 경기의 연속 선수/공 트래킹 데이터는 공개 웹에서 합법적으로 확보하기 어렵다.' },
        { level: 'high', text: '방송 영상 CV 추출 경로는 정확도, 저작권, 비용 문제가 동시에 커진다.' },
        { level: 'medium', text: '현재 데모가 공개 샘플 기반임을 계속 표시하지 않으면 사용자가 범위를 오해할 수 있다.' },
      ],
      next: [
        '개발 상태를 보류로 유지하고 데이터 확보 의사결정부터 진행.',
        '대안으로 이벤트 데이터 기반 하이라이트 후보 탐색기 범위를 검토.',
      ],
    },
    {
      id: 'solar',
      order: '03',
      name: 'Solar System Simulator',
      label: '태양계 3D 시뮬레이터',
      state: 'Claude parity 반영 완료',
      health: 'active',
      progress: 100,
      stack: ['HTML5', 'JavaScript', 'Three.js', 'WebGL', 'GitHub Pages'],
      summary: '현재 날짜 기준 태양, 행성, 달, 주요 위성, 탐사선, 외태양계 구조, 라그랑주점, 성간/가상 천체를 배치하고 타임머신, 카메라 포커싱, 정보 패널을 제공하는 3D 천체 시뮬레이터.',
      verdict: 'Codex와 Claude 버전을 각각 공개 주소로 분리했고, Claude가 2026-05-24에 확장한 주요 위성·탐사선·라그랑주점·오무아무아·제9행성·EHT·가르강튀아/웜홀 장면을 Codex 구조로 다시 구현했다. Codex 보고서는 기능 매트릭스, 검증 증거, lane separation 설명을 추가해 왕먀오 박사가 바로 비교 리뷰할 수 있게 보강했다.',
      links: [
        {
          label: 'Solar Project - Codex',
          url: '../solar-project-codex/',
          probe: 'GitHub Pages 200',
          note: '태양계 전체, 외태양계, 성간 랜드마크, 위성/탐사선/라그랑주/특수천체/인터스텔라 포커스 포함',
        },
        {
          label: 'Solar Project - Claude',
          url: '../solar-project-claude/',
          probe: 'GitHub Pages 200',
          note: 'Claude가 별도 lane에서 유지하는 단일 HTML 기반 비교 버전',
        },
      ],
      review: [
        '두 버전을 `solar-project-codex`와 `solar-project-claude` 공개 경로로 분리해 왕먀오 박사에게 바로 공유하고 비교할 수 있게 했다.',
        '연도 이동 버튼은 현재 위치 대비 즉시 점프가 아니라, 목표 날짜까지 중간 날짜를 거치며 재생되는 방식으로 수정했다.',
        'Codex 버전은 실제 지구 텍스처, 구름층, 야간 조명, 달 텍스처, 목성 대적점, 화성/수성 표면 디테일, 토성 고리 결을 추가했다.',
        '포커스 메뉴는 태양계 전체, 카이퍼 벨트, 오르트 구름, Alpha Centauri, 40 Eridani A, Sagittarius A* 사건의 지평선까지 확장됐다.',
        '사건의 지평선 시각화는 단순 검은 구체에서 accretion disk, 렌즈 링, 헤일로, 제트가 있는 블랙홀 장면으로 보강됐다.',
        'Claude의 최신 확장 범위를 참고하되 Codex 폴더 안에서만 주요 위성, 탐사선, L1-L5, 목성 트로이군, 카모오알레와, 오무아무아, 제9행성, EHT M87*, 웜홀, 가르강튀아, 밀러/맨/에드먼즈 행성을 별도 레이어로 구현했다.',
        'Claude의 모바일 패널 닫기/복원 UX도 Codex 방식으로 구현해 상태, 정보, 부산 달·조석 패널을 chip dock에서 다시 복원할 수 있게 했다.',
        '태양계 Codex 보고서에는 parity map, 검증 evidence, Claude handoff 항목을 추가해 보고서 자체의 품질과 피드백 가능성을 높였다.',
      ],
      risks: [
        { level: 'medium', text: '천체 위치는 간소화된 궤도요소 기반이므로 실제 항법·관측용 정밀 천문력으로 오해하지 않게 안내가 필요하다.' },
        { level: 'medium', text: '조석/물때 기능으로 확장할 경우 관측 지점, 조화상수, 예측 모델의 출처를 별도로 고정해야 한다.' },
        { level: 'low', text: '고해상도 텍스처, 입자, 특수 장면, 선택 토글이 늘어났으므로 저사양 모바일 성능 검증은 계속 필요하다.' },
      ],
      next: [
        '정확도 출처와 모델 한계 고지 패널 추가.',
        '왕먀오 박사 피드백 기준으로 UI 문구, 모바일 배치, 특수천체 확대 카메라 거리를 한 번 더 조정.',
      ],
    },
    {
      id: 'inst',
      order: '04',
      name: 'INST EXTRACTOR',
      label: '음원 보컬 제거 / Inst 추출기',
      state: 'GPU 추출 검증 완료',
      health: 'active',
      progress: 88,
      stack: ['Python 3.11', 'FastAPI', 'Demucs', 'PyTorch CUDA', 'HTML5 UI'],
      summary: '사용자가 업로드한 음원에서 보컬 stem을 제거하고 반주용 inst WAV 파일을 생성하는 변환 프로그램.',
      verdict: 'RTX 4060 Ti 환경에서 CUDA, Demucs 직접 호출, HTTP /extract 경로가 모두 통과했다. 일본어 등 비ASCII 파일명에서 결과 WAV 생성 후 500이 나던 응답 헤더 오류도 수정되어 실제 업로드 파일 다운로드까지 가능한 상태다.',
      links: [
        {
          label: 'INST EXTRACTOR 브리핑',
          url: './inst-extractor/',
          probe: 'GitHub Pages 200',
          note: 'GPU 검증 결과와 비ASCII 파일명 오류 수정 기록',
        },
        {
          label: 'GitHub 저장소',
          url: 'https://github.com/gmpark-creator/inst-extractor',
          probe: 'Repo',
          note: 'NEXT_DESKTOP_STEPS.md / CODEX_TO_CLAUDE.md 포함',
        },
      ],
      review: [
        '`separate_instrumental()`은 모델 로드, CUDA/CPU 자동 분기, stem 분리, vocals 제외 합산, WAV 저장까지 구현되어 있다.',
        '집 데스크탑에서 `POST /extract`가 실제 MP3를 받아 235.519초 WAV, 41.5MB 결과물을 반환하는 것을 확인했다.',
        '원본 파일명에 일본어가 들어가면 `X-Original-Filename` 헤더 인코딩 때문에 500이 발생하던 문제를 percent-encoded 헤더로 수정했다.',
        '현재 남은 핵심은 디렉터 청취 기준의 음질 평가와 모델별 결과 비교다.',
      ],
      risks: [
        { level: 'medium', text: '긴 음원은 처리 시간이 길어 브라우저 요청 타임아웃이나 진행률 부재 문제가 드러날 수 있다.' },
        { level: 'medium', text: '모델별 결과 품질 차이가 있어 htdemucs, htdemucs_ft, htdemucs_6s, mdx_extra를 실제 샘플로 비교해야 한다.' },
        { level: 'low', text: 'RTX 4060 Ti가 8GB 모델로 확인되어 매우 긴 음원과 고품질 모델 조합에서는 VRAM 모니터링이 필요하다.' },
      ],
      next: [
        '브라우저 UI에서 실제 보유 음원을 업로드하고 결과 WAV를 청취 평가.',
        'htdemucs, htdemucs_ft, htdemucs_6s, mdx_extra 모델별 품질과 처리 시간을 비교.',
        '긴 음원에서 필요하면 진행률 API와 작업 큐를 다음 단계로 구현.',
      ],
    },
  ],
  improvements: [
    {
      title: '태양계 Claude parity 반영',
      body: 'Claude가 오늘 확장한 주요 위성, 탐사선, 라그랑주점, 특수/인터스텔라 장면을 Codex 구조로 따로 구현하고 두 공개 경로를 계속 분리했다.',
    },
    {
      title: '시간 이동 방식 개선',
      body: '1년 전후 이동은 즉시 날짜 점프가 아니라 현재 시점에서 목표 시점까지 시간이 흐르듯 재생되도록 바뀌었다.',
    },
    {
      title: 'Codex 보고서 품질 보강',
      body: '태양계 Codex 보고서에 feature matrix, 검증 evidence, Claude handoff 기준을 추가해 왕먀오 박사와 Claude가 같은 기준으로 비교할 수 있게 했다.',
    },
    {
      title: '4번 프로젝트 인수인계 완료',
      body: 'INST EXTRACTOR는 RTX 4060 Ti에서 GPU 추출과 HTTP 다운로드 검증을 통과했고, 비ASCII 파일명 응답 오류까지 수정했다.',
    },
  ],
  actions: [
    '태양계 Codex/Claude 공개 링크와 Codex 보고서를 왕먀오 박사에게 공유하고 비주얼·조작감 피드백을 받는다.',
    'INST EXTRACTOR는 디렉터 청취 기준으로 모델별 보컬 제거 품질을 비교한다.',
    'AIS 프로젝트는 데이터 공급원과 갱신 실패 정책을 운영 문서로 고정한다.',
    '스포츠 프로젝트는 트래킹 데이터 라이선스 경로가 결정될 때까지 신규 기능 개발을 멈춘다.',
  ],
};
